"""add inbound partner and logging

Revision ID: 5b98ac38267c
Revises: 878fbb1df108
Create Date: 2026-04-08 10:41:24.550217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b98ac38267c'
down_revision = '878fbb1df108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request_ip', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_key.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id', 'external_id', name='_partner_external_id_uc')
    )
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_inbound_enabled', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('allowed_ips', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('daily_limit', sa.Integer(), server_default='10000000', nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_partner', sa.Boolean(), server_default='0', nullable=False))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_partner')

    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_column('daily_limit')
        batch_op.drop_column('allowed_ips')
        batch_op.drop_column('is_inbound_enabled')

    op.drop_table('inbound_log')
    # ### end Alembic commands ###
