"""Add detailed fee structure to Payment model

Revision ID: 647b6440f16c
Revises: 8ff098ca9bed
Create Date: 2025-12-02 15:34:45.723736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647b6440f16c'
down_revision = '8ff098ca9bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payer_fee', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('merchant_fee', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('payment_method')
        batch_op.drop_column('merchant_fee')
        batch_op.drop_column('payer_fee')

    # ### end Alembic commands ###
