"""Add payment_id to Transaction model

Revision ID: 6611974129dc
Revises: dbb667d26f7e
Create Date: 2025-11-30 21:44:25.427361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6611974129dc'
down_revision = 'dbb667d26f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(op.f('fk_transaction_payment_id_payment'), 'payment', ['payment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('fk_transaction_payment_id_payment'), type_='foreignkey')
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###
