"""add split bill models

Revision ID: 8a9965df6e77
Revises: 647b6440f16c
Create Date: 2025-12-03 17:27:14.428452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9965df6e77'
down_revision = '647b6440f16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('split_bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('split_bill_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('split_bill_id', sa.Integer(), nullable=False),
    sa.Column('participant_user_id', sa.Integer(), nullable=True),
    sa.Column('participant_email', sa.String(length=120), nullable=False),
    sa.Column('amount_due', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['split_bill_id'], ['split_bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('split_bill_participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_split_bill_participant_participant_email'), ['participant_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('split_bill_participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_split_bill_participant_participant_email'))

    op.drop_table('split_bill_participant')
    op.drop_table('split_bill')
    # ### end Alembic commands ###
