"""Remove unused game models

Revision ID: dbb667d26f7e
Revises: 348f413e8c22
Create Date: 2025-11-30 12:17:25.694936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb667d26f7e'
down_revision = '348f413e8c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_game_state')
    op.drop_table('game_level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_level',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('level_number', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('expected_command', sa.VARCHAR(length=255), nullable=False),
    sa.Column('reward_amount', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_number')
    )
    op.create_table('user_game_state',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('level_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['game_level.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###
